### ISSUE TITLE
AU plugin crashed LPX 11.0.1

### ISSUE THREAD

**Issue by jeremyfuksa** [asb2m10/dexed#435]
After installing version 0.9.7 of the AU plugin, Logic Pro X hangs during startup. Here is my `auvaltool` output:
```

    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'Dexd' - 'DGSB'
--------------------------------------------------
Manufacturer String: Digital Suburban
AudioUnit Name: Dexed
Component Version: 1.0.0 (0x10000)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
Time to open AudioUnit:         6.061 ms
WARM:
Time to open AudioUnit:         0.526  ms
This AudioUnit is a version 2 implementation.
FIRST TIME:
Time for initialization:        0.008 ms

* * PASS
--------------------------------------------------
VERIFYING DEFAULT SCOPE FORMATS:
Input Scope Bus Configuration:
 Default Bus Count:0

Output Scope Bus Configuration:
 Default Bus Count:1
    Bus Name: output
    Default Format: AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
    Has Channel Layouts: 0x640001 0x650002 0x660002 0x670002 0x6A0002 
    Default Layout:
	Tag=0x650002, Num Chan Descs=0

* * PASS
--------------------------------------------------
VERIFYING REQUIRED PROPERTIES:

* * PASS
--------------------------------------------------
VERIFYING RECOMMENDED PROPERTIES:
  VERIFYING PROPERTY: Latency
    PASS

* * PASS
--------------------------------------------------
VERIFYING OPTIONAL PROPERTIES:
  VERIFYING PROPERTY: Tail Time
    PASS
  VERIFYING PROPERTY: Bypass Effect
    PASS

* * PASS
--------------------------------------------------
VERIFYING SPECIAL PROPERTIES:

VERIFYING CUSTOM UI
Cocoa Views Available: 1
  JUCE_AUCocoaViewClass_a434eaef7a527463
    PASS

DEFAULT PRESET: 0, Name: Say Again.

HAS FACTORY PRESETS
    ID:   0    Name: Say Again.
    ID:   1    Name: LAURIE    
    ID:   2    Name: Beatmehrdr
    ID:   3    Name: PHAROH    
    ID:   4    Name: Chroma 5 Y
    ID:   5    Name: Lavitar  Y
    ID:   6    Name: SloSwl //Y
    ID:   7    Name: OB GenvivY
    ID:   8    Name: SAW EM UP 
    ID:   9    Name: LFORez ++Y
    ID:  10    Name: ENCOUNTERS
    ID:  11    Name: Thunder  3
    ID:  12    Name: EchoEcho 3
    ID:  13    Name: -ANALOG 1-
    ID:  14    Name: P.ICE 25.1
    ID:  15    Name: FLEXI    4
    ID:  16    Name: ARP 2600  
    ID:  17    Name: Arp+BuzzRs
    ID:  18    Name: TRW       
    ID:  19    Name: MIRIDOR 1 
    ID:  20    Name: DEVIL TACK
    ID:  21    Name: RUMBLE   1
    ID:  22    Name: CASCADE 21
    ID:  23    Name: C,D,Eb,F  
    ID:  24    Name: TundStatc^
    ID:  25    Name: -WOBBLE 1-
    ID:  26    Name: FILTER-SWP
    ID:  27    Name: SAHARA    
    ID:  28    Name: ELECTRON 1
    ID:  29    Name: BANKS, T. 
    ID:  30    Name: Slow3D Pad
    ID:  31    Name: LFO SWEEP 

VERIFYING CLASS INFO
    PASS

TESTING HOST CALLBACKS
    PASS

* * PASS
--------------------------------------------------
PUBLISHED PARAMETER INFO:

# # # 155 Global Scope Parameters:
Parameter ID:461506
Name: OP3 F FINE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:13936686
Name: Resonance
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:18860417
Name: OP4 SWITCH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:39488398
Name: OP4 R KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:54381413
Name: OP3 EG LEVEL 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:54381414
Name: OP3 EG LEVEL 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:54381415
Name: OP3 EG LEVEL 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:54381416
Name: OP3 EG LEVEL 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:76906603
Name: LFO PM DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:83778312
Name: OP4 L KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:87883758
Name: OP6 L SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:113682572
Name: OP3 KEY VELOCITY
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:120931152
Name: OP6 OUTPUT LEVEL
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:166275286
Name: OP4 F COARSE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:183464132
Name: OP4 EG LEVEL 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:183464133
Name: OP4 EG LEVEL 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:183464134
Name: OP4 EG LEVEL 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:183464135
Name: OP4 EG LEVEL 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:193438730
Name: OP1 OSC DETUNE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:225838369
Name: Output
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:245668343
Name: PITCH EG LEVEL 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:245668344
Name: PITCH EG LEVEL 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:245668345
Name: PITCH EG LEVEL 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:245668346
Name: PITCH EG LEVEL 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:247261233
Name: OP3 R SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:260451264
Name: OP2 BREAK POINT
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:286950124
Name: OP3 A MOD SENS.
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:304157504
Name: OP2 EG RATE 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:304157505
Name: OP2 EG RATE 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:304157506
Name: OP2 EG RATE 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:304157507
Name: OP2 EG RATE 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:312546851
Name: OP5 EG LEVEL 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:312546852
Name: OP5 EG LEVEL 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:312546853
Name: OP5 EG LEVEL 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:312546854
Name: OP5 EG LEVEL 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:322521449
Name: OP2 OSC DETUNE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:332891405
Name: OP3 R KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:362788791
Name: OP3 F COARSE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:377181319
Name: OP3 L KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:405134819
Name: OP2 F FINE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:423533730
Name: OP3 SWITCH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:441629570
Name: OP6 EG LEVEL 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:441629571
Name: OP6 EG LEVEL 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:441629572
Name: OP6 EG LEVEL 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:441629573
Name: OP6 EG LEVEL 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:446784886
Name: OP2 RATE SCALING
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:451604168
Name: OP3 OSC DETUNE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:474949364
Name: OP6 R SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:500127466
Name: OP2 L SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:501240629
Name: OP1 OUTPUT LEVEL
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:522313007
Name: PITCH EG RATE 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:522313008
Name: PITCH EG RATE 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:522313009
Name: PITCH EG RATE 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:522313010
Name: PITCH EG RATE 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:553854271
Name: OP1 BREAK POINT
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:559302296
Name: OP2 F COARSE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:572034034
Name: OP6 RATE SCALING
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:580353131
Name: OP2 A MOD SENS.
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:580686887
Name: OP4 OSC DETUNE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:591125381
Name: FEEDBACK
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:619241197
Name: OP2 KEY VELOCITY
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:626294412
Name: OP2 R KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:626489777
Name: OP5 OUTPUT LEVEL
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:654689793
Name: OP3 EG RATE 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:654689794
Name: OP3 EG RATE 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:654689795
Name: OP3 EG RATE 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:654689796
Name: OP3 EG RATE 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:670584326
Name: OP2 L KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:709769606
Name: OP5 OSC DETUNE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:727815597
Name: OP5 L SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:744490345
Name: OP6 KEY VELOCITY
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:755815801
Name: OP1 F COARSE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:809808132
Name: OP1 F FINE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:828207043
Name: OP2 SWITCH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:838852325
Name: OP6 OSC DETUNE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:864601167
Name: ALGORITHM
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:873756138
Name: OP1 A MOD SENS.
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:887193072
Name: OP2 R SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:894251399
Name: LFO KEY SYNC
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:919697419
Name: OP1 R KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:933925215
Name: OP6 F FINE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:952343511
Name: OP1 RATE SCALING
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:963987333
Name: OP1 L KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1005222082
Name: OP4 EG RATE 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1005222083
Name: OP4 EG RATE 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1005222084
Name: OP4 EG RATE 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1005222085
Name: OP4 EG RATE 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1077592659
Name: OP5 RATE SCALING
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1114881203
Name: OP5 R SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1124799822
Name: OP1 KEY VELOCITY
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1132048402
Name: OP4 OUTPUT LEVEL
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1140059305
Name: OP1 L SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1232880356
Name: OP1 SWITCH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1234322884
Name: OP6 BREAK POINT
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1250048970
Name: OP5 KEY VELOCITY
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1338598528
Name: OP5 F FINE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1355754371
Name: OP5 EG RATE 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1355754372
Name: OP5 EG RATE 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1355754373
Name: OP5 EG RATE 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1355754374
Name: OP5 EG RATE 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1356997439
Name: OP6 SWITCH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1367747436
Name: OP4 L SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1410798685
Name: MASTER TUNE ADJ
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
WARNING: retrievedValue = 0.999939 (was 1.000000), Parameter did not retain maximum value when set
  -parameter PASS

Parameter ID:1417310346
Name: P MODE SENS.
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1451743780
Name: LFO WAVE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1527124911
Name: OP1 R SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1527725891
Name: OP5 BREAK POINT
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1554224751
Name: OP6 A MOD SENS.
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1583151284
Name: OP4 RATE SCALING
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1600166032
Name: OP6 R KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1637607027
Name: OP3 OUTPUT LEVEL
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1644455946
Name: OP6 L KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1692075801
Name: TRANSPOSE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1706286660
Name: OP6 EG RATE 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1706286661
Name: OP6 EG RATE 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1706286662
Name: OP6 EG RATE 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1706286663
Name: OP6 EG RATE 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1743271841
Name: OP4 F FINE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1754130429
Name: OSC KEY SYNC
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1754813042
Name: OP4 R SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1755607595
Name: OP4 KEY VELOCITY
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1761670752
Name: OP5 SWITCH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1811150163
Name: OP1 MODE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1821128898
Name: OP4 BREAK POINT
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1839779314
Name: OP2 MODE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1847627758
Name: OP5 A MOD SENS.
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1852039002
Name: LFO AM DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1868408465
Name: OP3 MODE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1893569039
Name: OP5 R KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1897037616
Name: OP4 MODE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1920731924
Name: OP6 F COARSE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1925666767
Name: OP5 MODE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1937858953
Name: OP5 L KEY SCALE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1943699623
Name: OP1 EG LEVEL 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1943699624
Name: OP1 EG LEVEL 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1943699625
Name: OP1 EG LEVEL 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1943699626
Name: OP1 EG LEVEL 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:1954295918
Name: OP6 MODE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2007679275
Name: OP3 L SCALE DEPTH
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2029770765
Name: Cutoff
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2036946840
Name: LFO DELAY
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2051120732
Name: LFO SPEED
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2072782342
Name: OP2 EG LEVEL 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2072782343
Name: OP2 EG LEVEL 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2072782344
Name: OP2 EG LEVEL 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2072782345
Name: OP2 EG LEVEL 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2088709909
Name: OP3 RATE SCALING
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2101108863
Name: OP1 EG RATE 1
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2101108864
Name: OP1 EG RATE 2
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2101108865
Name: OP1 EG RATE 3
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2101108866
Name: OP1 EG RATE 4
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2114531905
Name: OP3 BREAK POINT
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2117245429
Name: OP5 F COARSE
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2141030765
Name: OP4 A MOD SENS.
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Parameter ID:2143165652
Name: OP2 OUTPUT LEVEL
Parameter Type: Generic
Values: Minimum = 0, Default = 0, Maximum = 1
Flags: Values Have Strings, High Resolution, Can Ramp, Readable, Writable 
  -parameter PASS

Testing that parameters retain value across reset and initialization
  PASS

* * PASS
--------------------------------------------------
FORMAT TESTS:

Reported Channel Capabilities (explicit):
      [0, 1]  [0, 2]  

No Input, Output Chans:
0-1   0-2   0-4   0-5   0-6   0-7   0-8
X     X                                   

# # AudioChannelLayouts (5), Output Scope:
ChannelLayout is Writable: T
The Unit publishes the following Channel Layouts:
  0x640001, 0x650002, 0x660002, 0x670002, 0x6A0002, 

Is Audio Channel Layout Available:
Mono    Stereo  Binau.  AU_4    Ambi.   AU_5    AU_5_0  AU_6    AU_6_0  AU_7_0  AU_7_0F AU_8    AU_5_1  AU_6_1  AU_7_1  AU_7_1F 
X       X       X                                                                                                               

Current Format:AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
Current Format Tag = 0x650002, New Format Tag = 0x640001, Success - did not reset format with mis-matched layout

Current Format:AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
Current Format Tag = 0x650002, New Format Tag = 0x650002, Successsful

Current Format:AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
Current Format Tag = 0x650002, New Format Tag = 0x6A0002, Successsful

* * PASS
--------------------------------------------------
RENDER TESTS:

Output Format: AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
Render Test at 512 frames
Slicing Render Test at 64 frames
  PASS


Render Test at 64 frames, sample rate: 22050 Hz
Render Test at 137 frames, sample rate: 96000 Hz
Render Test at 4096 frames, sample rate: 48000 Hz
Render Test at 4096 frames, sample rate: 192000 Hz
Render Test at 4096 frames, sample rate: 11025 Hz
Render Test at 512 frames, sample rate: 44100 Hz
  PASS

1 Channel Test:
Render Test at 512 frames
zsh: segmentation fault  auval -v aumu Dexd DGSB
```

**Comment by asb2m10** [comment]
Logic seems to ignore that Dexed is specifically a stereo synth. This is now fixed, you can test this with this debug build: https://github.com/asb2m10/dexed/actions/runs/10021731481

**Comment by jeremyfuksa** [comment]
This new build still fails AU validation. Logic will load OK now, but when you try to load Dexed, it says the component is damaged and needs to move to the trash.

Running `auvaltool` prompted again to remove the component:

![CleanShot 2024-08-02 at 09 34 33@2x](https://github.com/user-attachments/assets/e25a572f-d83d-4ea7-a99a-17e677c2e588)

```
    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'Dexd' - 'DGSB'
--------------------------------------------------
Manufacturer String: Digital Suburban
AudioUnit Name: Dexed
Component Version: 1.0.0 (0x10000)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF
```

**Comment by asb2m10** [comment]
The development builds are not yet signed by Apple, that why get this error. If you execute this from the command line, it should work out :

`xattr -r -d com.apple.quarantine /Library/Audio/Plug-Ins/Components/Dexed.component`
